package lsp

type BrainrotEntry struct {
	Term        string
	Description string
}

var rpConnectMapper = map[string]BrainrotEntry{
	"yes":           {"ongod frfr 💯🔥", "An enthusiastic affirmation, absolutely true."},
	"no":            {"nah fam 🚫🙅", "Casual denial or rejection."},
	"cool":          {"rizzed up 😎✨", "Something or someone impressive, full of style."},
	"wow":           {"sheeesh 😱💥", "Expression of amazement or admiration."},
	"excuse me":     {"skibbidi toilet 🚽💀", "Used humorously to get attention or show surprise."},
	"okay":          {"bet 🤑👌", "Confirmation or agreement to a plan or statement."},
	"right?":        {"ain't no cap 🤥✋", "Seeking affirmation that something is true."},
	"crazy":         {"wildin' 🤪😵", "Acting in an outrageous or unpredictable way."},
	"seriously":     {"deadass 🧢💀", "Sincerely or without joking."},
	"friend":        {"bruv 👊👊", "Casual term for a close friend or buddy."},
	"for real":      {"frfr 🤞💯", "Genuinely, honestly."},
	"lit":           {"fire 🔥🔥", "Something exciting or outstanding."},
	"laughing":      {"LMFAO 😂💀", "Bursting into laughter."},
	"amazing":       {"top-tier 🏆💫", "Of the highest quality."},
	"awesome":       {"goated 🐐👌", "Considered the greatest of all time."},
	"weird":         {"sus 👀🤨", "Suspicious or questionable behavior."},
	"hello":         {"yo yo 👋✨", "Slangy greeting."},
	"goodbye":       {"peace out ✌️🌊", "Casual way to say farewell."},
	"hungry":        {"starvin' marvin 🍔🍟", "Feeling very hungry."},
	"understand":    {"I feel ya 🤔👌", "Expressing empathy or agreement."},
	"love":          {"mad love ❤️😍", "A strong affection for someone or something."},
	"dislike":       {"not a vibe 🚫👎", "Showing disapproval or a lack of interest."},
	"genius":        {"big brain 🧠💡", "Someone highly intelligent."},
	"strong":        {"built diff 💪🦾", "Unique and resilient individual."},
	"winner":        {"dub secured 🏆💯", "Victory or success achieved."},
	"joke":          {"big yikes 😬💀", "Something cringeworthy or embarrassing."},
	"fashion":       {"drip 💧👗", "Stylish clothing or appearance."},
	"awkward":       {"hella cringe 😬🙅", "Causing discomfort or embarrassment."},
	"perfect":       {"chef’s kiss 👌💋", "Something flawless or well done."},
	"serious":       {"deadass fr 🧢🤐", "Very earnest or genuine."},
	"super":         {"mega lit 🚀🔥", "Something highly exciting or cool."},
	"mistake":       {"oopsie 💀🚫", "An error or blunder."},
	"tired":         {"big nap vibes 😴💤", "Feeling very sleepy or exhausted."},
	"happy":         {"vibe check ✅😄", "A positive or joyful feeling."},
	"excited":       {"lowkey hyped 🚀✨", "Eagerly anticipating something."},
	"beautiful":     {"no cap, stunning 😍💫", "Extremely attractive or pleasing."},
	"angry":         {"mad salty 😤🧂", "Annoyed or frustrated."},
	"confused":      {"brain fried 🤯😵💫", "Feeling bewildered or mentally exhausted."},
	"exhausted":     {"donezo 💤🥱", "Completely worn out."},
	"real talk":     {"facts only 🧠📈", "Speaking truthfully or honestly."},
	"attention":     {"peep this 👀👂", "Listen closely or pay attention."},
	"scared":        {"shook 🥶😱", "Feeling frightened or startled."},
	"legend":        {"big dawg 🐐💪", "A person admired for their skills or achievements."},
	"gossip":        {"spill the tea ☕👀", "Sharing juicy or scandalous information."},
	"really?":       {"fo real fo real 🧐🤔", "Expressing disbelief or surprise."},
	"calm down":     {"chillax 🧊😌", "Encouraging someone to relax."},
	"smart":         {"IQ 200 🧠💥", "Exceptionally intelligent."},
	"winning":       {"dub secured 🏆🔥", "Achieving victory or success."},
	"procrastinate": {"catching Zzz's 😴🛌", "Putting off tasks or responsibilities."},
}
