version: '3'

dotenv:
  - .env
  - .env.local
  - .versions

vars:
  TARGET_DIR: target
  TOOLS_BIN_DIR: '{{.USER_WORKING_DIR}}/bin'
  VERSION:
    sh: git describe --tags 2>/dev/null | sed 's/^v//' || echo "0.0.0"

includes:
  tools: ./taskfiles/tools.yml

tasks:
  fmt:
    desc: Format code and tidy modules
    deps:
      - tools:install-golangci-lint
    cmds:
      - '{{.TOOLS_BIN_DIR}}/golangci-lint fmt cmd/... internal/... public/...'
      - go mod tidy

  lint:
    desc: Run linter on code
    deps:
      - tools:install-golangci-lint
    cmds:
      - '{{.TOOLS_BIN_DIR}}/golangci-lint run cmd/... internal/... public/...'
