// Copyright 2025 Redpanda Data, Inc.

package docs

// DeprecatedComponentTemplate is an old (now unused) template for generating
// documentation. It has been replace with public methods for exporting template
// data, allowing you to use whichever template suits your needs.
// TODO: V5 Remove this
var DeprecatedComponentTemplate = DeprecatedFieldsTemplate(false) + `
= {{.Name}}
:type: {{.Type}}
:status: {{.Status}}
{{if gt (len .Categories) 0 -}}
:categories: {{.Categories}}
{{end}}


////
     THIS FILE IS AUTOGENERATED!

     To make changes please edit the corresponding source file under internal/impl/<provider>.
////


component_type_dropdown::[]


{{if eq .Status "beta" -}}

{{end -}}
{{if eq .Status "experimental" -}}

{{end -}}
{{if eq .Status "deprecated" -}}
[CAUTION]
====
This component is deprecated and will be removed in the next major version release. Please consider moving onto <<alternatives,alternative components>>.
====
{{end -}}


{{if gt (len .Summary) 0 -}}
{{.Summary}}
{{end -}}{{if gt (len .Version) 0}}
Introduced in version {{.Version}}.
{{end}}
{{if eq .CommonConfigYAML .AdvancedConfigYAML -}}
` + "```yml" + `
# Config fields, showing default values
{{.CommonConfigYAML -}}
` + "```" + `
{{else}}
[tabs]
======
Common::
+
--

` + "```yml" + `
# Common config fields, showing default values
{{.CommonConfigYAML -}}
` + "```" + `

--
Advanced::
+
--

` + "```yml" + `
# All config fields, showing default values
{{.AdvancedConfig -}}
` + "```" + `

--
======
{{end -}}
{{if gt (len .Description) 0}}
{{.Description}}
{{end}}
{{if and (le (len .Fields) 4) (gt (len .Fields) 0) -}}
== Fields

{{template "field_docs" . -}}
{{end -}}

{{if gt (len .Examples) 0 -}}
== Examples

[tabs]
======
{{range $i, $example := .Examples -}}
{{$example.Title}}::
+
--

{{if gt (len $example.Summary) 0 -}}
{{$example.Summary}}
{{end}}
{{if gt (len $example.Config) 0 -}}
` + "```yaml" + `{{$example.Config}}` + "```" + `
{{end}}
--
{{end -}}
======

{{end -}}

{{if gt (len .Fields) 4 -}}
== Fields

{{template "field_docs" . -}}
{{end -}}

{{if gt (len .Footnotes) 0 -}}
{{.Footnotes}}
{{end}}
`
