// Copyright 2026 Redpanda Data, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// gen-case-tables emits src/stdlib/case_tables.ts: Go's unicode.CaseRanges
// serialized as a flat number array. The TypeScript implementation consumes
// it to perform Unicode SIMPLE case mapping (per-codepoint 1:1), which the
// spec requires for .uppercase()/.lowercase() (Section 13.5) and which
// JavaScript's built-in toUpperCase()/toLowerCase() (FULL case mapping)
// cannot provide. Generating from the Go toolchain's own tables guarantees
// the two engines agree by construction.
//
// Regenerate (from internal/bloblang2/ts):
//
//	task gen:case-tables
package main

import (
	"fmt"
	"os"
	"runtime"
	"unicode"
)

func main() {
	w := os.Stdout
	fmt.Fprintf(w, `// Code generated by scripts/gen-case-tables (%s); DO NOT EDIT.
//
// Go's unicode.CaseRanges as a flat array of 4-tuples:
//   [lo, hi, deltaUpper, deltaLower, ...]
// A delta equal to UPPER_LOWER (0x110001) marks an alternating
// Upper,Lower,Upper,Lower... sequence (see Go's unicode.UpperLower).
// Used by case_mapping.ts for Unicode simple case mapping.

export const UPPER_LOWER = %d;

// prettier-ignore
export const CASE_RANGES: number[] = [
`, runtime.Version(), unicode.UpperLower)
	for _, cr := range unicode.CaseRanges {
		fmt.Fprintf(w, "  %d, %d, %d, %d,\n",
			cr.Lo, cr.Hi,
			cr.Delta[unicode.UpperCase], cr.Delta[unicode.LowerCase])
	}
	fmt.Fprintln(w, "];")
}
